language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm test
sudo: required
addons:
    chrome: stable

#sending coverage data to Coveralls
after_script: cat coverage/*/lcov.info | node_modules/coveralls/bin/coveralls.js